"""revision

Revision ID: 0780377e04bf
Revises: 2c932c277e48
Create Date: 2024-07-13 21:21:17.647582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0780377e04bf'
down_revision = '2c932c277e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.drop_column('expense_name')
        batch_op.drop_column('expense_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_amount', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('expense_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('amount')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
