"""revision

Revision ID: 2eb2ecbe1271
Revises: f5cb45da99a7
Create Date: 2024-07-13 22:10:09.964873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb2ecbe1271'
down_revision = 'f5cb45da99a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.drop_column('budget_name')
        batch_op.drop_column('budget_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_amount', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('budget_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
