"""revision

Revision ID: f5cb45da99a7
Revises: 0780377e04bf
Create Date: 2024-07-13 21:37:17.126248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cb45da99a7'
down_revision = '0780377e04bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_amount', sa.Integer(), nullable=True))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('budget_amount')

    # ### end Alembic commands ###
